sudo: required	
services: docker
before_install:
  - docker-compose up --build -d
  - docker-compose ps
script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrete
  - docker-compose exec --env 'RAILS_ENV=test' web rails test